#pragma once
#include <iostream>
#include <fstream>
#include <sstream>
#include <string>
#include <vector>
#include <deque>
#include <list>
#include <map>
#include <unordered_map>
#include <set>
#include <unordered_set>
#include <stack>
#include <queue>
#include <algorithm>
#include <memory>
#include <functional>
#include <type_traits>
#include <utility>
#include <bitset>
#include <limits>
#include <chrono>
#include <thread>
#include <mutex>
#include <atomic>
#include <condition_variable>