using Amethyst.Common.Diagnostics;
using Amethyst.Common.Extensions;
using Amethyst.Common.Tracking;
using K4os.Hash.xxHash;
using System.Diagnostics;
using System.Text;
using System.Text.RegularExpressions;

namespace Amethyst.Common.Utility
{
    public class FuzzyStringComparer : IEqualityComparer<string>
    {
        private readonly int _maxDistance;
        public FuzzyStringComparer(int maxDistance = 1)
        {
            _maxDistance = maxDistance;
        }
        public bool Equals(string? x, string? y)
        {
            if (x == null || y == null)
                return x == y;
            return Utils.CompareSymbolsWithThreshold(x, y, _maxDistance);
        }
        public int GetHashCode(string obj)
        {
            return obj.GetHashCode();
        }
    }

    public static partial class Utils
    {
        public static T Benchmark<T>(string name, Func<T> action)
        {
            var sw = Stopwatch.StartNew();
            T res = action();
            sw.Stop();
            Logger.Debug($"[Benchmark] {name} took {sw.Elapsed.TotalMilliseconds:F0} ms");
            return res;
        }

        public static void Benchmark(string name, Action action)
        {
            var sw = Stopwatch.StartNew();
            action();
            sw.Stop();
            Logger.Debug($"[Benchmark] {name} took {sw.Elapsed.TotalMilliseconds:F0} ms");
        }

        [GeneratedRegex(@"^\s*///\s*@\s*(symbolgeneration|symbols)\s*$", RegexOptions.Multiline | RegexOptions.IgnoreCase)]
        private static partial Regex SymbolGenerationMarker();

        public static string[] CreateIncludeFile(string includeFile, string[] inputDirs, IEnumerable<FileChange> files)
        {
            List<string> willBeParsed = [];
            var sb = new StringBuilder();
            sb.AppendLine("// This file was generated by Amethyst Symbol Generator.");
            foreach (var header in files)
            {
                // Reuse FileTracker-cached content when available; only re-read as a fallback.
                string content = header.Content ?? File.ReadAllText(header.FilePath);
                if (!SymbolGenerationMarker().Match(content).Success)
                    continue;
                willBeParsed.Add(header.FilePath.NormalizeSlashes());
                string relativePath = GetRelativePathFromInputs(inputDirs, header.FilePath);
                sb.AppendLine(@$"#include ""{relativePath.NormalizeSlashes()}""");
            }
            sb.AppendLine("// End of generated file.");
            File.WriteAllText(includeFile, sb.ToString());
            return [.. willBeParsed];
        }

        /// <summary>
        /// Find which input directory a file belongs to and return the relative path from that directory.
        /// </summary>
        public static string GetRelativePathFromInputs(string[] inputDirs, string filePath)
        {
            string normalized = filePath.Replace('\\', '/');
            foreach (var inputDir in inputDirs)
            {
                string dirNorm = inputDir.Replace('\\', '/');
                if (!dirNorm.EndsWith('/')) dirNorm += '/';
                if (normalized.StartsWith(dirNorm, StringComparison.OrdinalIgnoreCase))
                    return Path.GetRelativePath(inputDir, filePath);
            }
            return Path.GetRelativePath(inputDirs[0], filePath);
        }

        public static void CreateDefinitionFile(string defFile, IEnumerable<string> mangledNames)
        {
            var sb = new StringBuilder();
            sb.AppendLine("; This file was generated by Amethyst Symbol Generator.");
            sb.AppendLine(@"LIBRARY ""Minecraft.Windows.exe""");
            sb.AppendLine("EXPORTS");
            foreach (var name in mangledNames)
            {
                sb.AppendLine($"    {name}");
            }
            sb.AppendLine("; End of generated file.");
            File.WriteAllText(defFile, sb.ToString());
        }

        public static void WritePrefixedString(this BinaryWriter writer, string str) {
            byte[] bytes = Encoding.UTF8.GetBytes(str);
            writer.Write(bytes.Length);
            writer.Write(bytes);
        }

        public static string ReadPrefixedString(this BinaryReader reader) {
            int length = reader.ReadInt32();
            byte[] bytes = reader.ReadBytes(length);
            return Encoding.UTF8.GetString(bytes);
        }

        public static void WriteHashedName(this BinaryWriter writer, string name, bool includeDebug) {
            byte[] nameBytes = Encoding.UTF8.GetBytes(name);
            writer.Write(XXH64.DigestOf(nameBytes));
            if (includeDebug)
                writer.WritePrefixedString(name);
        }

        public static void WriteCompiledSignature(this BinaryWriter writer, string signature) {
            var tokens = signature.Split(' ', StringSplitOptions.RemoveEmptyEntries);
            writer.Write((uint)tokens.Length);
            foreach (var token in tokens) {
                if (token.StartsWith('?')) {
                    writer.Write((byte)0);  // value (unused)
                    writer.Write((byte)0);  // present = false (wildcard)
                } else {
                    writer.Write(Convert.ToByte(token, 16));  // value
                    writer.Write((byte)1);                     // present = true
                }
            }
        }

        public static void Align(this BinaryWriter writer, int alignment = 16, byte pad = 0x00) {
            long pos = writer.BaseStream.Position;
            int padding = (int)((alignment - (pos % alignment)) % alignment);
            for (int i = 0; i < padding; i++)
                writer.Write(pad);
        }

        public static IEnumerable<IEnumerable<T>> ChunkBy<T>(this IEnumerable<T> source, int chunkSize) {
            if (source == null)
                throw new ArgumentNullException(nameof(source));
            if (chunkSize <= 0)
                throw new ArgumentOutOfRangeException(nameof(chunkSize));

            using var enumerator = source.GetEnumerator();
            while (enumerator.MoveNext()) {
                yield return TakeChunk(enumerator, chunkSize);
            }
        }

        private static IEnumerable<T> TakeChunk<T>(this IEnumerator<T> enumerator, int chunkSize) {
            int count = 0;
            do {
                yield return enumerator.Current;
                count++;
            } while (count < chunkSize && enumerator.MoveNext());
        }

        public static int LevenshteinDistance(string a, string b) {
            int[,] dp = new int[a.Length + 1, b.Length + 1];
            for (int i = 0; i <= a.Length; i++)
                dp[i, 0] = i;
            for (int j = 0; j <= b.Length; j++)
                dp[0, j] = j;

            for (int i = 1; i <= a.Length; i++)
                for (int j = 1; j <= b.Length; j++) {
                    int cost = a[i - 1] == b[j - 1] ? 0 : 1;
                    dp[i, j] = Math.Min(
                        Math.Min(dp[i - 1, j] + 1, dp[i, j - 1] + 1),
                        dp[i - 1, j - 1] + cost
                    );
                }

            return dp[a.Length, b.Length];
        }

        public static bool CompareSymbolsWithThreshold(string a, string b, int maxDistance = 1) {
            if (a == b)
                return true;
            if (a.Length != b.Length)
                return false;

            int mismatches = 0;
            for (int i = 0; i < a.Length; i++) {
                if (a[i] != b[i]) {
                    mismatches++;
                }
                if (mismatches > maxDistance)
                    return false;
            }
            return true;
        }
    }
}
