using Amethyst.Common.Diagnostics;
using Amethyst.Common.Extensions;
using Amethyst.Common.Tracking;
using System.Diagnostics;
using System.Text;
using System.Text.RegularExpressions;

namespace Amethyst.Common.Utility
{
    public static partial class Utils
    {
        public static T Benchmark<T>(string name, Func<T> action)
        {
            var sw = Stopwatch.StartNew();
            T res = action();
            sw.Stop();
            Logger.Debug($"[Benchmark] {name} took {sw.Elapsed.TotalMilliseconds:F0} ms");
            return res;
        }

        public static void Benchmark(string name, Action action)
        {
            var sw = Stopwatch.StartNew();
            action();
            sw.Stop();
            Logger.Debug($"[Benchmark] {name} took {sw.Elapsed.TotalMilliseconds:F0} ms");
        }

        [GeneratedRegex(@"^\s*///\s*@\s*(symbolgeneration|symbols)\s*$", RegexOptions.Multiline | RegexOptions.IgnoreCase)]
        private static partial Regex SymbolGenerationMarker();

        public static string[] CreateIncludeFile(string includeFile, string inputDir, IEnumerable<FileChange> files)
        {
            List<string> willBeParsed = [];
            var sb = new StringBuilder();
            sb.AppendLine("// This file was generated by Amethyst Symbol Generator.");
            foreach (var header in files)
            {
                if (!SymbolGenerationMarker().Match(File.ReadAllText(header.FilePath)).Success)
                    continue;
                willBeParsed.Add(header.FilePath.NormalizeSlashes());
                sb.AppendLine(@$"#include ""{Path.GetRelativePath(inputDir, header.FilePath).NormalizeSlashes()}""");
            }
            sb.AppendLine("// End of generated file.");
            File.WriteAllText(includeFile, sb.ToString());
            return [.. willBeParsed];
        }

        public static void CreateDefinitionFile(string defFile, IEnumerable<string> mangledNames)
        {
            var sb = new StringBuilder();
            sb.AppendLine("; This file was generated by Amethyst Symbol Generator.");
            sb.AppendLine(@"LIBRARY ""Minecraft.Windows.exe""");
            sb.AppendLine("EXPORTS");
            foreach (var name in mangledNames)
            {
                sb.AppendLine($"    {name}");
            }
            sb.AppendLine("; End of generated file.");
            File.WriteAllText(defFile, sb.ToString());
        }

        public static void WritePrefixedString(this BinaryWriter writer, string str) {
            byte[] bytes = Encoding.UTF8.GetBytes(str);
            writer.Write(bytes.Length);
            writer.Write(bytes);
        }

        public static string ReadPrefixedString(this BinaryReader reader) {
            int length = reader.ReadInt32();
            byte[] bytes = reader.ReadBytes(length);
            return Encoding.UTF8.GetString(bytes);
        }

        public static void Align(this BinaryWriter writer, int alignment = 16, byte pad = 0x00) {
            long pos = writer.BaseStream.Position;
            int padding = (int)((alignment - (pos % alignment)) % alignment);
            for (int i = 0; i < padding; i++)
                writer.Write(pad);
        }

        public static IEnumerable<IEnumerable<T>> ChunkBy<T>(this IEnumerable<T> source, int chunkSize) {
            if (source == null)
                throw new ArgumentNullException(nameof(source));
            if (chunkSize <= 0)
                throw new ArgumentOutOfRangeException(nameof(chunkSize));

            using var enumerator = source.GetEnumerator();
            while (enumerator.MoveNext()) {
                yield return TakeChunk(enumerator, chunkSize);
            }
        }

        private static IEnumerable<T> TakeChunk<T>(this IEnumerator<T> enumerator, int chunkSize) {
            int count = 0;
            do {
                yield return enumerator.Current;
                count++;
            } while (count < chunkSize && enumerator.MoveNext());
        }

        public static int LevenshteinDistance(string a, string b) {
            int[,] dp = new int[a.Length + 1, b.Length + 1];
            for (int i = 0; i <= a.Length; i++)
                dp[i, 0] = i;
            for (int j = 0; j <= b.Length; j++)
                dp[0, j] = j;

            for (int i = 1; i <= a.Length; i++)
                for (int j = 1; j <= b.Length; j++) {
                    int cost = a[i - 1] == b[j - 1] ? 0 : 1;
                    dp[i, j] = Math.Min(
                        Math.Min(dp[i - 1, j] + 1, dp[i, j - 1] + 1),
                        dp[i - 1, j - 1] + cost
                    );
                }

            return dp[a.Length, b.Length];
        }

        public static bool CompareSymbolsWithThreshold(string symbolA, string symbolB, int charMatch = 3)
        {
            if (symbolA == symbolB)
                return true;
            if (symbolA.Length != symbolB.Length) 
                return false;
            int misses = 0;
            for (int i = 0; i < symbolA.Length; i++) {
                if (symbolA[i] != symbolB[i])
                    misses++;
                if (misses > charMatch)
                    return false;
            }
            return true;
        }
    }
}
